# Generated by Django 4.1.4 on 2022-12-26 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Имя', models.CharField(default='Иванан', max_length=1024)),
                ('Фамилия', models.CharField(default='Иванов', max_length=1024)),
                ('Отчество', models.CharField(default='Иванович', max_length=1024)),
                ('День_рождения', models.DateField()),
                ('Рост', models.IntegerField(default=170)),
                ('Вес', models.IntegerField(default=80)),
                ('Пол', models.BooleanField(default=True)),
                ('Лелефон', models.IntegerField()),
            ],
        ),
    ]
