# Generated by Django 4.1.4 on 2022-12-26 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Лелефон',
        ),
        migrations.AddField(
            model_name='user',
            name='Email',
            field=models.EmailField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='Телефон',
            field=models.IntegerField(default=11),
        ),
    ]
